[tool.poetry]
name = "messaging-intro"
version = "0.1.0"
description = ""
authors = ["alonisser <alonisser@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pika = "^1.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
